sudo: required
services:
    - docker

before_install:
    - docker build -t $DOCKER_ID/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true $DOCKER_ID/react-test npm test

after-success:
    - docker build -t $DOCKER_ID/multi-client ./client
    - docker build -t $DOCKER_ID/multi-server ./server
    - docker build -t $DOCKER_ID/multi-nginx ./nginx
    - docker build -t $DOCKER_ID/multi-worker ./worker
    # push images to dockerhub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push $DOCKER_ID/multi-client
    - docker push $DOCKER_ID/multi-server
    - docker push $DOCKER_ID/multi-nginx
    - docker push $DOCKER_ID/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-909787369163"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY